# PyTorch Basics: Tensors and Operations

Welcome to your first PyTorch tutorial! In this notebook, we'll cover:
- What tensors are and why they're important
- Creating tensors in various ways
- Tensor operations
- Indexing, slicing, and reshaping
- GPU acceleration

## What is a Tensor?

A **tensor** is a multi-dimensional array, the fundamental data structure in PyTorch.

```
Scalar (0D):    5

Vector (1D):    [1, 2, 3, 4]

Matrix (2D):    [[1, 2, 3],
                 [4, 5, 6]]

3D Tensor:      [[[1, 2],
                  [3, 4]],
                 [[5, 6],
                  [7, 8]]]
```

Think of tensors as:
- **Numbers with superpowers** - they can represent complex data
- **GPU-friendly** - they can be moved to GPU for fast computation
- **Differentiable** - they track gradients for backpropagation


In [15]:
# First, let's import PyTorch
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")


PyTorch version: 2.8.0
CUDA available: False


## 1. Creating Tensors

There are many ways to create tensors. Let's explore the most common ones.

### 1.1 From Python Lists


In [16]:
# Create a 1D tensor (vector)
vector = torch.tensor([1, 2, 3, 4])
print("1D Tensor (vector):")
print(vector)
print(f"Shape: {vector.shape}")
print(f"Dimensions: {vector.ndim}\n")

# Create a 2D tensor (matrix)
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print("2D Tensor (matrix):")
print(matrix)
print(f"Shape: {matrix.shape}")
print(f"Dimensions: {matrix.ndim}\n")

# Create a 3D tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]],
                          [[5, 6], [7, 8]]])
print("3D Tensor:")
print(tensor_3d)
print(f"Shape: {tensor_3d.shape}")
print(f"Dimensions: {tensor_3d.ndim}")


1D Tensor (vector):
tensor([1, 2, 3, 4])
Shape: torch.Size([4])
Dimensions: 1

2D Tensor (matrix):
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Dimensions: 2

3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Dimensions: 3


### 1.2 Special Tensors (Zeros, Ones, Identity)


In [17]:
# Tensor filled with zeros
zeros = torch.zeros(2, 3)
print("Zeros tensor (2x3):")
print(zeros)
print()

# Tensor filled with ones
ones = torch.ones(2, 3)
print("Ones tensor (2x3):")
print(ones)
print()

# Identity matrix
identity = torch.eye(3)
print("Identity matrix (3x3):")
print(identity)
print()

# Tensor filled with a specific value
filled = torch.full((2, 3), 7.5)
print("Filled tensor with 7.5:")
print(filled)


Zeros tensor (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones tensor (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Identity matrix (3x3):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Filled tensor with 7.5:
tensor([[7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000]])


### 1.3 Random Tensors

Random tensors are crucial for:
- Initializing neural network weights
- Data augmentation
- Stochastic processes


In [18]:
# Random tensor with uniform distribution [0, 1)
rand_uniform = torch.rand(2, 3)
print("Random uniform [0, 1):")
print(rand_uniform)
print()

# Random tensor with normal distribution (mean=0, std=1)
rand_normal = torch.randn(2, 3)
print("Random normal (0, 1):")
print(rand_normal)
print()

# Random integers
rand_int = torch.randint(low=0, high=10, size=(2, 3))
print("Random integers [0, 10):")
print(rand_int)
print()

# Set seed for reproducibility
torch.manual_seed(42)
print("With seed 42:")
print(torch.randn(2, 2))

torch.manual_seed(42)
print("\nWith same seed 42 (same result):")
print(torch.randn(2, 2))


Random uniform [0, 1):
tensor([[0.5216, 0.2008, 0.6297],
        [0.8218, 0.0641, 0.9796]])

Random normal (0, 1):
tensor([[ 1.7422, -1.3275,  0.2538],
        [-0.4729,  0.1490, -0.9967]])

Random integers [0, 10):
tensor([[0, 5, 1],
        [1, 2, 6]])

With seed 42:
tensor([[0.3367, 0.1288],
        [0.2345, 0.2303]])

With same seed 42 (same result):
tensor([[0.3367, 0.1288],
        [0.2345, 0.2303]])


### 1.4 From NumPy Arrays

PyTorch and NumPy work seamlessly together!


In [19]:
# Create NumPy array
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("NumPy array:")
print(np_array)
print(type(np_array))
print()

# Convert to PyTorch tensor
tensor_from_np = torch.from_numpy(np_array)
print("PyTorch tensor from NumPy:")
print(tensor_from_np)
print(type(tensor_from_np))
print()

# Convert back to NumPy
back_to_np = tensor_from_np.numpy()
print("Back to NumPy:")
print(back_to_np)
print(type(back_to_np))

# ⚠️ Warning: They share memory!
print("\n⚠️ Memory sharing demonstration:")
np_array_2 = np.array([[1, 2], [3, 4]])
tensor_shared = torch.from_numpy(np_array_2)
np_array_2[0, 0] = 999
print("Modified NumPy array:")
print(np_array_2)
print("\nPyTorch tensor (also modified!):")
print(tensor_shared)


NumPy array:
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

PyTorch tensor from NumPy:
tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>

Back to NumPy:
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

⚠️ Memory sharing demonstration:
Modified NumPy array:
[[999   2]
 [  3   4]]

PyTorch tensor (also modified!):
tensor([[999,   2],
        [  3,   4]])


## 2. Tensor Properties

Tensors have several important properties:

```
┌─────────────────────────────────────┐
│         Tensor Properties           │
├─────────────────────────────────────┤
│  • shape/size  - dimensions         │
│  • dtype       - data type          │
│  • device      - CPU or GPU         │
│  • requires_grad - gradient tracking│
└─────────────────────────────────────┘
```


In [20]:
# Create a sample tensor
x = torch.randn(2, 3, 4)

print("Tensor properties:")
print(f"Shape: {x.shape}")  # or x.size()
print(f"Data type: {x.dtype}")
print(f"Device: {x.device}")
print(f"Requires gradient: {x.requires_grad}")
print(f"Number of dimensions: {x.ndim}")
print(f"Total number of elements: {x.numel()}")

# Data types in PyTorch
print("\n" + "="*50)
print("Common data types:")
print("="*50)

# Integer types
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print(f"int32: {int_tensor.dtype}")

long_tensor = torch.tensor([1, 2, 3], dtype=torch.long)
print(f"long (int64): {long_tensor.dtype}")

# Float types
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(f"float32: {float_tensor.dtype}")

double_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
print(f"float64 (double): {double_tensor.dtype}")

# Boolean
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)
print(f"bool: {bool_tensor.dtype}")

# Type conversion
print("\nType conversion:")
x = torch.tensor([1, 2, 3])
print(f"Original: {x.dtype}")
print(f"To float: {x.float().dtype}")
print(f"To double: {x.double().dtype}")
print(f"To int: {x.int().dtype}")


Tensor properties:
Shape: torch.Size([2, 3, 4])
Data type: torch.float32
Device: cpu
Requires gradient: False
Number of dimensions: 3
Total number of elements: 24

Common data types:
int32: torch.int32
long (int64): torch.int64
float32: torch.float32
float64 (double): torch.float64
bool: torch.bool

Type conversion:
Original: torch.int64
To float: torch.float32
To double: torch.float64
To int: torch.int32


## 3. Tensor Operations

### 3.1 Basic Arithmetic

```
Element-wise operations:
  [1, 2]  +  [3, 4]  =  [4, 6]
  [1, 2]  *  [3, 4]  =  [3, 8]
```


In [21]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float)

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)
print()

# Addition
print("Addition (a + b):")
print(a + b)
print(torch.add(a, b))  # Alternative
print()

# Subtraction
print("Subtraction (a - b):")
print(a - b)
print()

# Multiplication (element-wise)
print("Multiplication (a * b):")
print(a * b)
print()

# Division
print("Division (a / b):")
print(a / b)
print()

# Power
print("Power (a ** 2):")
print(a ** 2)
print()

# In-place operations (modify the tensor)
print("In-place addition (a += 1):")
a_copy = a.clone()
a_copy.add_(1)  # Note the underscore
print(a_copy)


Tensor a:
tensor([[1., 2.],
        [3., 4.]])

Tensor b:
tensor([[5., 6.],
        [7., 8.]])

Addition (a + b):
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])

Subtraction (a - b):
tensor([[-4., -4.],
        [-4., -4.]])

Multiplication (a * b):
tensor([[ 5., 12.],
        [21., 32.]])

Division (a / b):
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

Power (a ** 2):
tensor([[ 1.,  4.],
        [ 9., 16.]])

In-place addition (a += 1):
tensor([[2., 3.],
        [4., 5.]])


### 3.2 Matrix Operations

```
Matrix Multiplication:

  [1, 2]   @   [5, 6]   =   [19, 22]
  [3, 4]       [7, 8]       [43, 50]

  (2x2)       (2x2)         (2x2)
```


In [22]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float)

# Matrix multiplication
print("Matrix multiplication (a @ b):")
print(a @ b)
print(torch.mm(a, b))  # Alternative for 2D
print(torch.matmul(a, b))  # More general
print()

# Transpose
print("Transpose:")
print(a.T)  # or a.transpose(0, 1)
print()

# Batch matrix multiplication
batch1 = torch.randn(10, 3, 4)  # 10 matrices of shape 3x4
batch2 = torch.randn(10, 4, 5)  # 10 matrices of shape 4x5
result = torch.bmm(batch1, batch2)  # 10 matrices of shape 3x5
print(f"Batch matrix multiplication: {result.shape}")
print()

# Dot product (for vectors)
v1 = torch.tensor([1, 2, 3], dtype=torch.float)
v2 = torch.tensor([4, 5, 6], dtype=torch.float)
print(f"Dot product: {torch.dot(v1, v2)}")
print(f"Manual calculation: 1*4 + 2*5 + 3*6 = {1*4 + 2*5 + 3*6}")


Matrix multiplication (a @ b):
tensor([[19., 22.],
        [43., 50.]])
tensor([[19., 22.],
        [43., 50.]])
tensor([[19., 22.],
        [43., 50.]])

Transpose:
tensor([[1., 3.],
        [2., 4.]])

Batch matrix multiplication: torch.Size([10, 3, 5])

Dot product: 32.0
Manual calculation: 1*4 + 2*5 + 3*6 = 32


### 3.3 Aggregation Operations


In [23]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.float)

print("Original tensor:")
print(x)
print()

# Sum
print(f"Sum of all elements: {x.sum()}")
print(f"Sum along rows (dim=0): {x.sum(dim=0)}")
print(f"Sum along columns (dim=1): {x.sum(dim=1)}")
print()

# Mean
print(f"Mean: {x.mean()}")
print(f"Mean along rows: {x.mean(dim=0)}")
print(f"Mean along columns: {x.mean(dim=1)}")
print()

# Min and Max
print(f"Min: {x.min()}")
print(f"Max: {x.max()}")
print(f"Argmin (index of min): {x.argmin()}")
print(f"Argmax (index of max): {x.argmax()}")
print()

# Standard deviation and variance
print(f"Standard deviation: {x.std()}")
print(f"Variance: {x.var()}")
print()

# Product
print(f"Product of all elements: {x.prod()}")


Original tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Sum of all elements: 21.0
Sum along rows (dim=0): tensor([5., 7., 9.])
Sum along columns (dim=1): tensor([ 6., 15.])

Mean: 3.5
Mean along rows: tensor([2.5000, 3.5000, 4.5000])
Mean along columns: tensor([2., 5.])

Min: 1.0
Max: 6.0
Argmin (index of min): 0
Argmax (index of max): 5

Standard deviation: 1.8708287477493286
Variance: 3.5

Product of all elements: 720.0


## 4. Indexing and Slicing

Similar to NumPy, but with some PyTorch-specific features.

```
Tensor indexing visualization:

    Col 0  Col 1  Col 2
Row 0: [1,    2,    3]
Row 1: [4,    5,    6]
Row 2: [7,    8,    9]

x[0, 1] = 2  (row 0, col 1)
x[:, 0] = [1, 4, 7]  (all rows, col 0)
x[1, :] = [4, 5, 6]  (row 1, all cols)
```


In [24]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Original tensor:")
print(x)
print()

# Single element
print(f"x[0, 1] = {x[0, 1]}")
print(f"x[1, 2] = {x[1, 2]}")
print()

# Entire row
print(f"First row x[0]: {x[0]}")
print(f"First row x[0, :]: {x[0, :]}")
print()

# Entire column
print(f"First column x[:, 0]: {x[:, 0]}")
print(f"Second column x[:, 1]: {x[:, 1]}")
print()

# Slicing
print(f"First two rows x[:2]: \n{x[:2]}")
print()
print(f"Last two columns x[:, 1:]: \n{x[:, 1:]}")
print()

# Advanced indexing
print(f"Rows 0 and 2 x[[0, 2]]: \n{x[[0, 2]]}")
print()

# Boolean indexing
print("Boolean indexing (elements > 5):")
mask = x > 5
print(f"Mask: \n{mask}")
print(f"Elements > 5: {x[mask]}")
print()

# Where
print("Using torch.where (if > 5, keep value, else 0):")
result = torch.where(x > 5, x, torch.tensor(0))
print(result)


Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

x[0, 1] = 2
x[1, 2] = 6

First row x[0]: tensor([1, 2, 3])
First row x[0, :]: tensor([1, 2, 3])

First column x[:, 0]: tensor([1, 4, 7])
Second column x[:, 1]: tensor([2, 5, 8])

First two rows x[:2]: 
tensor([[1, 2, 3],
        [4, 5, 6]])

Last two columns x[:, 1:]: 
tensor([[2, 3],
        [5, 6],
        [8, 9]])

Rows 0 and 2 x[[0, 2]]: 
tensor([[1, 2, 3],
        [7, 8, 9]])

Boolean indexing (elements > 5):
Mask: 
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
Elements > 5: tensor([6, 7, 8, 9])

Using torch.where (if > 5, keep value, else 0):
tensor([[0, 0, 0],
        [0, 0, 6],
        [7, 8, 9]])


## 5. Reshaping Tensors

Reshaping is crucial for neural networks where dimensions must match.

```
Reshape example:

[1, 2, 3, 4, 5, 6]  (shape: 6)
        ↓
[[1, 2, 3],         (shape: 2, 3)
 [4, 5, 6]]
        ↓
[[[1, 2],           (shape: 1, 3, 2)
  [3, 4],
  [5, 6]]]
```


In [25]:
x = torch.arange(1, 13)  # [1, 2, ..., 12]
print(f"Original: {x}")
print(f"Shape: {x.shape}")
print()

# Reshape using view
y = x.view(3, 4)
print("Reshaped to 3x4 using view:")
print(y)
print()

# Reshape using reshape (more flexible)
z = x.reshape(4, 3)
print("Reshaped to 4x3 using reshape:")
print(z)
print()

# Using -1 (infer dimension)
w = x.view(2, -1)  # PyTorch infers the second dimension
print("Reshaped to 2x? using view(2, -1):")
print(w)
print(f"Shape: {w.shape}")
print()

# Flatten
flattened = y.view(-1)
print(f"Flattened: {flattened}")
print()

# Add dimensions with unsqueeze
a = torch.tensor([1, 2, 3])
print(f"Original: {a.shape}")
print(f"Unsqueeze at dim 0: {a.unsqueeze(0).shape}")  # Add batch dimension
print(a.unsqueeze(0))
print(f"Unsqueeze at dim 1: {a.unsqueeze(1).shape}")  # Add feature dimension
print(a.unsqueeze(1))
print()

# Remove dimensions with squeeze
b = torch.tensor([[[1, 2, 3]]])
print(f"Original shape: {b.shape}")
print(f"After squeeze: {b.squeeze().shape}")
print()

# Transpose
c = torch.randn(2, 3, 4)
print(f"Original shape: {c.shape}")
print(f"Transpose dim 0 and 1: {c.transpose(0, 1).shape}")
print(f"Permute (2, 0, 1): {c.permute(2, 0, 1).shape}")


Original: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Shape: torch.Size([12])

Reshaped to 3x4 using view:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Reshaped to 4x3 using reshape:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Reshaped to 2x? using view(2, -1):
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
Shape: torch.Size([2, 6])

Flattened: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Original: torch.Size([3])
Unsqueeze at dim 0: torch.Size([1, 3])
tensor([[1, 2, 3]])
Unsqueeze at dim 1: torch.Size([3, 1])
tensor([[1],
        [2],
        [3]])

Original shape: torch.Size([1, 1, 3])
After squeeze: torch.Size([3])

Original shape: torch.Size([2, 3, 4])
Transpose dim 0 and 1: torch.Size([3, 2, 4])
Permute (2, 0, 1): torch.Size([4, 2, 3])


## 6. GPU Acceleration with CUDA

One of PyTorch's killer features is seamless GPU support.

```
CPU                    GPU (CUDA)
 ↓                        ↓
[Tensor] ──.cuda()──> [Tensor]
[Tensor] <──.cpu()─── [Tensor]
```


In [26]:
# Check CUDA availability
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA device count: {torch.cuda.device_count()}")

if torch.cuda.is_available():
    print(f"Current CUDA device: {torch.cuda.current_device()}")
    print(f"CUDA device name: {torch.cuda.get_device_name(0)}")

print()

# Create device object (works for CPU and GPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
print()

# Create tensor on CPU
x_cpu = torch.randn(3, 3)
print(f"CPU tensor device: {x_cpu.device}")

# Move to GPU (if available)
if torch.cuda.is_available():
    x_gpu = x_cpu.cuda()
    # Or use .to()
    x_gpu = x_cpu.to(device)
    print(f"GPU tensor device: {x_gpu.device}")
    
    # Create directly on GPU
    y_gpu = torch.randn(3, 3, device='cuda')
    print(f"Created on GPU: {y_gpu.device}")
    
    # Operations on GPU tensors
    z_gpu = x_gpu + y_gpu
    print(f"Result on GPU: {z_gpu.device}")
    
    # Move back to CPU
    z_cpu = z_gpu.cpu()
    print(f"Back to CPU: {z_cpu.device}")
else:
    print("CUDA not available. Running on CPU.")

print()

# Best practice: use device variable
print("Best practice example:")
a = torch.randn(1000, 1000, device=device)
b = torch.randn(1000, 1000, device=device)
c = a @ b
print(f"Computation done on: {c.device}")


CUDA available: False
CUDA device count: 0

Using device: cpu

CPU tensor device: cpu
CUDA not available. Running on CPU.

Best practice example:
Computation done on: cpu


## 7. Broadcasting

Broadcasting allows operations on tensors of different shapes.

```
Broadcasting rules:
1. If tensors have different number of dimensions,
   prepend 1s to the smaller shape
2. Dimensions are compatible if they're equal or one is 1

Example:
  (3, 4)  +  (4,)  →  (3, 4)  +  (1, 4)  →  (3, 4)
  
  [[1, 2, 3, 4],     [10, 20, 30, 40]
   [5, 6, 7, 8],  +  (broadcast to all rows)
   [9,10,11,12]]
```


In [27]:
# Example 1: Add scalar to tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original tensor:")
print(x)
print("\nAdd 10 to all elements:")
print(x + 10)
print()

# Example 2: Add vector to matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
vector = torch.tensor([10, 20, 30])
print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)
print("\nMatrix + Vector (broadcast):")
print(matrix + vector)
print()

# Example 3: Different shapes
a = torch.randn(3, 1)
b = torch.randn(1, 4)
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")
c = a + b
print(f"a + b shape: {c.shape}")  # (3, 4)
print()

# Example 4: Explicit broadcasting
x = torch.tensor([[1], [2], [3]])
y = torch.tensor([10, 20, 30, 40])
print(f"x shape: {x.shape}")
print(f"y shape: {y.shape}")
result = x + y
print(f"\nResult shape: {result.shape}")
print("Result:")
print(result)


Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Add 10 to all elements:
tensor([[11, 12, 13],
        [14, 15, 16]])

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

Vector:
tensor([10, 20, 30])

Matrix + Vector (broadcast):
tensor([[11, 22, 33],
        [14, 25, 36]])

a shape: torch.Size([3, 1])
b shape: torch.Size([1, 4])
a + b shape: torch.Size([3, 4])

x shape: torch.Size([3, 1])
y shape: torch.Size([4])

Result shape: torch.Size([3, 4])
Result:
tensor([[11, 21, 31, 41],
        [12, 22, 32, 42],
        [13, 23, 33, 43]])


## 📝 Summary

Congratulations! You've learned:

✅ What tensors are and why they're important  
✅ Creating tensors in multiple ways  
✅ Tensor properties (shape, dtype, device)  
✅ Basic and advanced tensor operations  
✅ Matrix multiplication and linear algebra  
✅ Indexing, slicing, and reshaping  
✅ GPU acceleration with CUDA  
✅ Broadcasting rules  

### Next Steps

- **Practice**: Try creating and manipulating tensors with different shapes
- **Next Tutorial**: `02_autograd.ipynb` - Learn about automatic differentiation
- **Challenge**: Implement a function to normalize a batch of images

### Additional Resources

- [PyTorch Tensor Documentation](https://pytorch.org/docs/stable/tensors.html)
- [PyTorch CUDA Semantics](https://pytorch.org/docs/stable/notes/cuda.html)
- [Broadcasting Semantics](https://pytorch.org/docs/stable/notes/broadcasting.html)


## 🎯 Practice Exercises

Try these exercises to reinforce your learning:


In [28]:
# Exercise 1: Create a 5x5 tensor with values from 1 to 25
# Your code here:


# Exercise 2: Extract the main diagonal from the tensor above
# Your code here:


# Exercise 3: Create two random tensors and compute their dot product
# Your code here:


# Exercise 4: Normalize a random tensor to have mean=0 and std=1
# Your code here:


# Exercise 5: Create a batch of 10 random 3x3 matrices and compute
# the determinant of each (hint: use torch.det or torch.linalg.det)
# Your code here:
